// <auto-generated />
using System;
using DATN_STMDT_THELIEMS.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DATN_STMDT_THELIEMS.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20241029174010_addTable")]
    partial class addTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Brands", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BRANDS");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Parent_id")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Parent_id");

                    b.ToTable("CATEGORIES");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Delivery_address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("District_id")
                        .HasColumnType("int");

                    b.Property<string>("Full_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Province_id")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.Property<int>("Ward_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User_id");

                    b.ToTable("DELIVERY_ADDRESSES");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Order_details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Order_id")
                        .HasColumnType("int");

                    b.Property<int?>("Product_price")
                        .HasColumnType("int");

                    b.Property<int?>("Product_quantity")
                        .HasColumnType("int");

                    b.Property<int?>("Product_variant_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Order_id");

                    b.HasIndex("Product_variant_id");

                    b.ToTable("ORDER_DETAILS");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Delivery_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Delivery_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Discount_amount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Order_time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Payment_method")
                        .HasColumnType("int");

                    b.Property<byte?>("Payment_status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("Payment_time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Shipping_cost")
                        .HasColumnType("int");

                    b.Property<int?>("Shipping_method")
                        .HasColumnType("int");

                    b.Property<int?>("Shop_id")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int?>("Total_price")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.Property<int?>("Voucher_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Shop_id");

                    b.HasIndex("User_id");

                    b.HasIndex("Voucher_id");

                    b.ToTable("ORDERS");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PERMISSIONS");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Product_Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Product_variant_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Product_variant_id");

                    b.ToTable("PRODUCT_IMAGES");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Product_part_image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Product_part_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Product_part_id");

                    b.ToTable("PRODUCT_PART_IMAGES");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Product_parts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Product_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Product_id");

                    b.ToTable("PRODUCT_PARTS");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Product_review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Like_count")
                        .HasColumnType("int");

                    b.Property<int>("Order_detail_id")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Order_detail_id");

                    b.HasIndex("User_id");

                    b.ToTable("PRODUCT_REVIEWS");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Product_variant_option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Product_variant_id")
                        .HasColumnType("int");

                    b.Property<int>("Variant_value_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Product_variant_id");

                    b.HasIndex("Variant_value_id");

                    b.ToTable("PRODUCT_VARIANT_OPTIONS");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Product_variants", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Product_id")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Product_id");

                    b.ToTable("PRODUCT_VARIANTS");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Brand_id")
                        .HasColumnType("int");

                    b.Property<int?>("Category_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Meta_keyword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Meta_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Product_link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Shop_id")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sold_count")
                        .HasColumnType("int");

                    b.Property<int?>("Supplier_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("View_count")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Brand_id");

                    b.HasIndex("Category_id");

                    b.HasIndex("Shop_id");

                    b.HasIndex("Supplier_id");

                    b.ToTable("PRODUCTS");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Review_media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Media")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Review_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Review_id");

                    b.ToTable("REVIEW_MEDIAS");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ROLES");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Role_Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Permission_id")
                        .HasColumnType("int");

                    b.Property<int>("Role_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Permission_id");

                    b.HasIndex("Role_id");

                    b.ToTable("ROLE_PERMISSIONS");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Shops", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User_id")
                        .IsUnique();

                    b.ToTable("SHOPS");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SUPPLIERS");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.User_shop_follow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Shop_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Shop_id");

                    b.HasIndex("User_id");

                    b.ToTable("USER_SHOP_FOLLOWS");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.User_shop_rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Shop_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Shop_id");

                    b.HasIndex("User_id");

                    b.ToTable("USER_SHOP_RATINGS");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Birthday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Full_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Is_seller")
                        .HasColumnType("tinyint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Role_id");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Variant_options", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VARIANT_OPTIONS");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Variant_values", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Variant_option_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Variant_option_id");

                    b.ToTable("VARIANT_VALUES");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Discount_type")
                        .HasColumnType("tinyint");

                    b.Property<int>("Discount_value")
                        .HasColumnType("int");

                    b.Property<DateTime>("End_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Max_discount")
                        .HasColumnType("int");

                    b.Property<int>("Min_order_value")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start_date")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.Property<string>("Voucher_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voucher_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UsersId");

                    b.ToTable("VOUCHERS");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Categories", b =>
                {
                    b.HasOne("DATN_STMDT_THELIEMS.Models.Categories", "Parent")
                        .WithMany()
                        .HasForeignKey("Parent_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Delivery_address", b =>
                {
                    b.HasOne("DATN_STMDT_THELIEMS.Models.Users", "Users")
                        .WithMany("Delivery_Addresses")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Order_details", b =>
                {
                    b.HasOne("DATN_STMDT_THELIEMS.Models.Orders", "Orders")
                        .WithMany("Order_Details")
                        .HasForeignKey("Order_id");

                    b.HasOne("DATN_STMDT_THELIEMS.Models.Product_variants", "Product_variants")
                        .WithMany("Order_Details")
                        .HasForeignKey("Product_variant_id");

                    b.Navigation("Orders");

                    b.Navigation("Product_variants");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Orders", b =>
                {
                    b.HasOne("DATN_STMDT_THELIEMS.Models.Shops", "Shops")
                        .WithMany("Orders")
                        .HasForeignKey("Shop_id");

                    b.HasOne("DATN_STMDT_THELIEMS.Models.Users", "Users")
                        .WithMany("Orders")
                        .HasForeignKey("User_id");

                    b.HasOne("DATN_STMDT_THELIEMS.Models.Voucher", "Voucher")
                        .WithMany("Orders")
                        .HasForeignKey("Voucher_id");

                    b.Navigation("Shops");

                    b.Navigation("Users");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Product_Image", b =>
                {
                    b.HasOne("DATN_STMDT_THELIEMS.Models.Product_variants", "product_Variants")
                        .WithMany("Product_Images")
                        .HasForeignKey("Product_variant_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product_Variants");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Product_part_image", b =>
                {
                    b.HasOne("DATN_STMDT_THELIEMS.Models.Product_parts", "Product_part")
                        .WithMany("Product_Part_Images")
                        .HasForeignKey("Product_part_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product_part");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Product_parts", b =>
                {
                    b.HasOne("DATN_STMDT_THELIEMS.Models.Products", "Products")
                        .WithMany("Product_Parts")
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Products");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Product_review", b =>
                {
                    b.HasOne("DATN_STMDT_THELIEMS.Models.Order_details", "Order_details")
                        .WithMany("Product_Reviews")
                        .HasForeignKey("Order_detail_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_STMDT_THELIEMS.Models.Users", "User")
                        .WithMany("Product_Reviews")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order_details");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Product_variant_option", b =>
                {
                    b.HasOne("DATN_STMDT_THELIEMS.Models.Product_variants", "product_Variants")
                        .WithMany("Product_Variant_Options")
                        .HasForeignKey("Product_variant_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_STMDT_THELIEMS.Models.Variant_values", "variant_values")
                        .WithMany("Product_Variant_Options")
                        .HasForeignKey("Variant_value_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product_Variants");

                    b.Navigation("variant_values");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Product_variants", b =>
                {
                    b.HasOne("DATN_STMDT_THELIEMS.Models.Products", "Products")
                        .WithMany("Product_Variants")
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Products");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Products", b =>
                {
                    b.HasOne("DATN_STMDT_THELIEMS.Models.Brands", "Brands")
                        .WithMany("Products")
                        .HasForeignKey("Brand_id");

                    b.HasOne("DATN_STMDT_THELIEMS.Models.Categories", "Categories")
                        .WithMany("Products")
                        .HasForeignKey("Category_id");

                    b.HasOne("DATN_STMDT_THELIEMS.Models.Shops", "Shops")
                        .WithMany("Products")
                        .HasForeignKey("Shop_id");

                    b.HasOne("DATN_STMDT_THELIEMS.Models.Supplier", "Suppliers")
                        .WithMany("Products")
                        .HasForeignKey("Supplier_id");

                    b.Navigation("Brands");

                    b.Navigation("Categories");

                    b.Navigation("Shops");

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Review_media", b =>
                {
                    b.HasOne("DATN_STMDT_THELIEMS.Models.Product_review", "product_Review")
                        .WithMany("Review_Medias")
                        .HasForeignKey("Review_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product_Review");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Role_Permission", b =>
                {
                    b.HasOne("DATN_STMDT_THELIEMS.Models.Permission", "Permission")
                        .WithMany("Role_Permissions")
                        .HasForeignKey("Permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_STMDT_THELIEMS.Models.Role", "Role")
                        .WithMany("Role_Permissions")
                        .HasForeignKey("Role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Shops", b =>
                {
                    b.HasOne("DATN_STMDT_THELIEMS.Models.Users", "Users")
                        .WithOne("Shops")
                        .HasForeignKey("DATN_STMDT_THELIEMS.Models.Shops", "User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.User_shop_follow", b =>
                {
                    b.HasOne("DATN_STMDT_THELIEMS.Models.Shops", "Shops")
                        .WithMany("User_Shop_Follows")
                        .HasForeignKey("Shop_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DATN_STMDT_THELIEMS.Models.Users", "Users")
                        .WithMany("User_Shop_Follows")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Shops");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.User_shop_rating", b =>
                {
                    b.HasOne("DATN_STMDT_THELIEMS.Models.Shops", "Shops")
                        .WithMany("User_Shop_Ratings")
                        .HasForeignKey("Shop_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DATN_STMDT_THELIEMS.Models.Users", "Users")
                        .WithMany("User_Shop_Ratings")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Shops");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Users", b =>
                {
                    b.HasOne("DATN_STMDT_THELIEMS.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("Role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Variant_values", b =>
                {
                    b.HasOne("DATN_STMDT_THELIEMS.Models.Variant_options", "Variant_Options")
                        .WithMany("Variant_values")
                        .HasForeignKey("Variant_option_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Variant_Options");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Voucher", b =>
                {
                    b.HasOne("DATN_STMDT_THELIEMS.Models.Users", "Users")
                        .WithMany("Vouchers")
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Brands", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Categories", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Order_details", b =>
                {
                    b.Navigation("Product_Reviews");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Orders", b =>
                {
                    b.Navigation("Order_Details");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Permission", b =>
                {
                    b.Navigation("Role_Permissions");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Product_parts", b =>
                {
                    b.Navigation("Product_Part_Images");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Product_review", b =>
                {
                    b.Navigation("Review_Medias");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Product_variants", b =>
                {
                    b.Navigation("Order_Details");

                    b.Navigation("Product_Images");

                    b.Navigation("Product_Variant_Options");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Products", b =>
                {
                    b.Navigation("Product_Parts");

                    b.Navigation("Product_Variants");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Role", b =>
                {
                    b.Navigation("Role_Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Shops", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("User_Shop_Follows");

                    b.Navigation("User_Shop_Ratings");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Users", b =>
                {
                    b.Navigation("Delivery_Addresses");

                    b.Navigation("Orders");

                    b.Navigation("Product_Reviews");

                    b.Navigation("Shops")
                        .IsRequired();

                    b.Navigation("User_Shop_Follows");

                    b.Navigation("User_Shop_Ratings");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Variant_options", b =>
                {
                    b.Navigation("Variant_values");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Variant_values", b =>
                {
                    b.Navigation("Product_Variant_Options");
                });

            modelBuilder.Entity("DATN_STMDT_THELIEMS.Models.Voucher", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
